version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./db:/var/www/html/db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: web
      PMA_PORT: 80
    depends_on:
      - web
    restart: unless-stopped
